-- ============================================================
-- AI Sales Analytics Agent
-- Database schema
-- ============================================================

-- ============================================================
-- Customers
-- ============================================================

CREATE TABLE customers (
    customer_id SERIAL PRIMARY KEY,
    company_name VARCHAR(255) NOT NULL,
    industry VARCHAR(100),
    country VARCHAR(100),
    company_size VARCHAR(50),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- Marketing campaigns
-- ============================================================

CREATE TABLE campaigns (
    campaign_id SERIAL PRIMARY KEY,
    campaign_name VARCHAR(255) NOT NULL,
    channel VARCHAR(100) NOT NULL,
    budget NUMERIC(12, 2),
    start_date DATE NOT NULL,
    end_date DATE
);

-- ============================================================
-- Leads
-- ============================================================

CREATE TABLE leads (
    lead_id SERIAL PRIMARY KEY,
    customer_id INTEGER REFERENCES customers(customer_id),
    campaign_id INTEGER REFERENCES campaigns(campaign_id),
    source VARCHAR(100) NOT NULL,
    status VARCHAR(50) NOT NULL,
    estimated_value NUMERIC(12, 2),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    assigned_manager VARCHAR(255)
);

-- ============================================================
-- Activities
-- ============================================================

CREATE TABLE activities (
    activity_id SERIAL PRIMARY KEY,
    lead_id INTEGER NOT NULL REFERENCES leads(lead_id),
    activity_type VARCHAR(50) NOT NULL,
    activity_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    manager_id VARCHAR(255),
    notes TEXT
);

-- ============================================================
-- Sales
-- ============================================================

CREATE TABLE sales (
    sale_id SERIAL PRIMARY KEY,
    lead_id INTEGER NOT NULL REFERENCES leads(lead_id),
    amount NUMERIC(12, 2) NOT NULL,
    sale_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(50) NOT NULL
);

-- ============================================================
-- Audit log
-- ============================================================

CREATE TABLE audit_log (
    id SERIAL PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tool_name VARCHAR(100) NOT NULL,
    status VARCHAR(50) NOT NULL,
    query TEXT,
    error_message TEXT
);
-- ============================================================
-- Business knowledge for AI analytics
-- ============================================================

-- Customers
COMMENT ON COLUMN customers.company_name IS
'Name of the customer company.';

COMMENT ON COLUMN customers.industry IS
'Industry in which the customer company operates.';

COMMENT ON COLUMN customers.company_size IS
'Approximate size of the customer company.';

-- Campaigns
COMMENT ON COLUMN campaigns.channel IS
'Marketing acquisition channel used for the campaign, such as Google Ads, LinkedIn, Email, 
Facebook, Referral, or Organic Search.';

COMMENT ON COLUMN campaigns.budget IS
'Marketing budget allocated to the campaign in USD.';

-- Leads
COMMENT ON COLUMN leads.customer_id IS
'Reference to the customer company associated with the lead. A new lead may not yet be 
associated with a known customer.';

COMMENT ON COLUMN leads.campaign_id IS
'Reference to the marketing campaign that generated the lead.';

COMMENT ON COLUMN leads.source IS
'Acquisition channel that generated the lead.';

COMMENT ON COLUMN leads.status IS
'Current position of the lead in the sales funnel: new, contacted, qualified, proposal, won, 
or lost.';

COMMENT ON COLUMN leads.estimated_value IS
'Estimated potential revenue of the lead in USD.';

COMMENT ON COLUMN leads.assigned_manager IS
'Sales manager responsible for the lead.';

-- Activities
COMMENT ON COLUMN activities.activity_type IS
'Type of sales activity performed for the lead: call, email, meeting, or message.';

COMMENT ON COLUMN activities.activity_date IS
'Date and time when the sales activity occurred.';

COMMENT ON COLUMN activities.manager_id IS
'Identifier of the manager who performed the activity.';

-- Sales
COMMENT ON COLUMN sales.amount IS
'Revenue generated by the sale in USD.';

COMMENT ON COLUMN sales.sale_date IS
'Date and time when the sale was completed.';

COMMENT ON COLUMN sales.status IS
'Current status of the sale, such as completed.';

-- Audit log
COMMENT ON COLUMN audit_log.tool_name IS
'Name of the MCP tool that generated the audit event.';

COMMENT ON COLUMN audit_log.status IS
'Execution status of the MCP tool call.';

COMMENT ON COLUMN audit_log.query IS
'SQL query or relevant operation associated with the tool call.';

COMMENT ON COLUMN audit_log.error_message IS
'Error message recorded when an MCP tool execution fails.';
